### ISSUE TITLE
Type d'application

### ISSUE THREAD

**Issue by moussadiallo** [Dibaa/Mon-projet#1]
Préciser de quel type d'application il s'agira ? web ou bureau(java) ?
Si c'est une application bureau ton projet sera un site web de présentation du logiciel
Aussi compléter la recherche documentaire.

**Comment by Dibaa** [comment]
Vu que nous sommes en retard avec java j'ai dut changer le projet 
Maintenant je fais et application web . La description est dans le Wiki
